services:
  splitfamily:
    build: .
    command: gunicorn project.wsgi:application --workers 3
    ports:
      - "6261:8000"
    volumes:
      - db-data:/dbs
    environment:
      - CONFIG_NAME=config.conf

networks:
  base:


volumes:
  db-data: